# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Education.create(title:"High School")
Education.create(title:"College freshman")
Education.create(title:"College Sophomore")
Education.create(title:"College Junior")
Education.create(title:"College Senior")
Education.create(title:"Masters Student")
Education.create(title:"PhD Student")
Education.create(title:"Professional")

Peducation.create(title:"High School")
Peducation.create(title:"College freshman")
Peducation.create(title:"College Sophomore")
Peducation.create(title:"College Junior")
Peducation.create(title:"College Senior")
Peducation.create(title:"Masters Student")
Peducation.create(title:"PhD Student")
Peducation.create(title:"Professional")

Interest.create(title:"Mobile App Development")
Interest.create(title:"Web Development")
Interest.create(title:"Data Science")
Interest.create(title:"Machine Learning")
Interest.create(title:"AR/VR")
Interest.create(title:"Hardware")
Interest.create(title:"IOT (internet of things)")
Interest.create(title:"Gaming")
Interest.create(title:"Other")

FirstPreference.create(title:"Python")
FirstPreference.create(title:"PHP")
FirstPreference.create(title:"Java")
FirstPreference.create(title:"C++")
FirstPreference.create(title:"C")
FirstPreference.create(title:"Haskell")
FirstPreference.create(title:"Scala")
FirstPreference.create(title:"Swift")
FirstPreference.create(title:"Objective-C")
FirstPreference.create(title:"Kotlin")
FirstPreference.create(title:"Ruby")
FirstPreference.create(title:"None: I am a complete beginner")
FirstPreference.create(title:"Other")

SecondPreference.create(title:"Python")
SecondPreference.create(title:"PHP")
SecondPreference.create(title:"Java")
SecondPreference.create(title:"C++")
SecondPreference.create(title:"C")
SecondPreference.create(title:"Haskell")
SecondPreference.create(title:"Scala")
SecondPreference.create(title:"Swift")
SecondPreference.create(title:"Objective-C")
SecondPreference.create(title:"Kotlin")
SecondPreference.create(title:"Ruby")
SecondPreference.create(title:"None: I am a complete beginner")
SecondPreference.create(title:"Other")

